### ISSUE TITLE
Nova Versão ?

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [cod3rcursos/meat-app-final#2]
Bom o projeto ficou bonito mas tem algumas coisas que não ficaram boas, por exemplo por  esse código ai em baixo. Tinha que ter um arquivo de cabeçalho separado, ficou muito acoplado. Outra coisa a falta de um Web Service de verdade usando por exemplo strongloop.
Veja um curso Grátis que tem paginação e WebService de verdade 👍 
http://kazale.com/curso-angular-2-aula-10-acesso-http-um-servidor-remoto/

Veja Um CRUD que fiz:
https://www.youtube.com/watch?v=wMsznbx-4rs&t=17s
https://github.com/DevJoseWeb/clienteBetha

Espero que as criticas construtivas faça surgir uma nova versão..

Abraço..

**Comment by tarsobessa** [comment]
Como mencionei em outro canal, não há necessidade de criar arquivo/classe para configurar cabeçalho, já que aplicação usa HttpInterceptors para isso.

Quem lê só essa mensagem até pode pensar que você sabe fazer críticas construtivas. Até parece.

Att,
